add_newline = false

[character]
success_symbol = "[μ ❯❯❯](bold green)"
error_symbol = "[π ❯❯❯](bold red)"

[python]
# symbol = " "
# Only use the `python3` binary to get the version.
python_binary = ["python3"]
disabled = true

[aws]
symbol = " "

[gcloud]
format = '|[$symbol($project)]($style)| '
style = "bright-black"

[kubernetes]
disabled = false
symbol = "⎈ "
style = "bright-yellow"
format = '|[$symbol$context(\($namespace\))]($style)| '

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncate_to_repo = false
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "bright-green"
format = '[$symbol$branch]($style)'

[golang]
symbol = " "
format = '[$symbol($version)]($style) '

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
# symbol = " "
disabled = true

[swift]
symbol = "ﯣ "

[env_var.NOHIST]
variable = "NOHIST"
format = "[$env_value]($style)"
