add_newline = false

[character]
success_symbol = "[%{μ ❯❯❯%5G%}](bold green)"
error_symbol = "[%{π ❯❯❯%5G%}](bold red)"

[python]
# symbol = " "
# Only use the `python3` binary to get the version.
python_binary = ["python3"]

[aws]
symbol = " "

[gcloud]
format = 'on [$symbol$account(\[$project\])]($style) %T '

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncate_to_repo = false
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
# symbol = " "

[swift]
symbol = "ﯣ "
